--1. SELECIONAR TODOS OS PROFS DO SEXO MASCULINO

--2. SELECIONAR TODOS OS CAMPOS NOME, SEXO E CIDADE DOS ALUNOS ATIVOS

--3. SELECIONAR APENAS OS NOMES DOS PROFESSORES COM O NIVEL (PLENO E SENIOR) ORDENADOS DE FORMA DECRESCENTE

--4. LISTE OS NOME EM MAIÚSCULO E AS CIDADES EM MINUSCULO DOS ALUNOS QUE A DATA DE CADATRO ESTEJA ENTRE 01/02/2013 ATÉ 28/02/2013

--5. LISTE OS PROFESSORES COM DATA DE ADMISSÃO SUPERIOR AO ANO DE 1998

--6. LISTE OS PROFESSORES CUJO O MêS DE ADMISSÃO SEJA Novembro OU Dezembro.

--7. LISTE OS CURSOS COM SUAS RESPECTIVAS AREAS

--8. LISTE o nome, salário, nome do perfil PROFESSORES E SEUS RESPECTIVOS PERFIS

--9. LISTE OS CAMPOS TurmaId, Nome do Curso, Turno (Deve aparecer na Tela: 'Manhã' se for 'M', 'Tarde' se for 'T' e 'Noite' se for 'N')

--10. LISTE OS CAMPOS TurmaId, Unidade(CASO NÃO EXISTA, INFORMAR A MENSAGEM 'Não informado'), Nome do Curso, Nome do Professor, Perfil do Professor, Turno 

--11. LISTE O SALARIO E O NOME E O SALÁRIO DO PROFESSOR QUE GANHA MAIS

--11b. LISTE O SALARIO E O NOME E O SALÁRIO DO PROFESSORES QUE GANHAM MENOS

--12. LISTE O CURSO COM MENOR CARGA HORARIA

--13. LISTE O TOTAL DE ALUNOS INATIVOS

--14. EXIBA O MENOR, A MÉDIA, O MAIOR E A SOMA DOS SALÁRIOS DOS PROFESSORES

--15. LISTE A QUANTOS PROFESSORES EXISTEM DO SEXO MASCULINO E FEMININO

--16. LISTE OS ALUNOS QUE NÃO ESTÃO INSCRITOS EM NENHUM CURSO

--17. LISTE TODOS ALUNOS E EXIBA OS CAMPOS NOME DO ALUNO, NOME DO CURSO, AREA DO CONHECIMENTO, UNIDADE(CASO NÃO EXISTA, INFORMAR A MENSAGEM 'Não informado'),
-- DATA DE INICIO (DD/MM/YY), HORA DE INICIO, 'HH:MM', NOME E PERFIL DO PROFESSOR, ID DA TURMA DOS CURSOS QUE COMEÇAM COM A LETRA 'A'.

--18. LISTE ID DO CURSO, NOME DO CURSO E A QUANTIDADE DE ALUNOS INSCRITOS